language: node_js
node_js:
  - "12"
script:
  - yarn test
  - yarn lint
  - yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: uwdata/falcon
  api_key:
    secure: Vm4Er/TK5Wg11BOMfwAClakHGFpcPtxr26MxoyaQI4WXQqi31jyMtZr3EnGW7AXtSCxeuQ3lAr1kx5hO6w4WK1C0H0yITuqu2amUu+Mm9F3yxN4aqWUsWmclI2SkCckBDkJ35crNyRvgWZQ6NBtTWajGnEHGQ/ZYlsqTkdwELk97EqWiZgJ8wWOg2yqeMHRWZhrNNHDS++oi6d0x1+VP3dcOyfvstXFovGMjaWncLB+pS4lYrEDVjnutZqjMXZXM9iSIWqzRleOjrxLeMCgPnw0swmFhYL7YbL6O+WpXQB7NZ9Cn+J6HI9g1bD9ssgGmCOiC9mEDxABIpnATb2mXbjNmf2e7CmdmZRKLz//6xb5/U6QmYmsUkOhMRN6jOk4imxCo4OwXfsEVQaLo1KfeHRYN2GxlJJGjXu3mjmPUmoDYrGrfxQ7gFl0gLcdIGkCBZGSEJlDFkYdeavEBt6+MSaVohYMbWeNm6GFGa/cdKa0+eybpNAMhy4Nh6Il+nESsSzhp5stFBNGeXbkUg/Q6wQi+OTfSa/T2xDJM0ZtOUC2ZImO0zcJXn8o4yl2HIC4/jNebHPtQ1HDe5ZvHmiZBsZfhIi6iq6fe0TD4YBCbxpbYsY/QQUTFpcd05MkWAEZaOvUlrZrL0N+OzMK4DwFpTrLxLnMZkrNz0m3xXuwtWEc=
